rancher:
  bootstrap:
    udev-bootstrap:
      image: rancher/os-udev:v0.4.0-dev
      labels:
        io.rancher.os.detach: false
        io.rancher.os.scope: system
      log_driver: json-file
      net: host
      uts: host
      privileged: true
      volumes:
      - /dev:/host/dev
      - /lib/modules:/lib/modules
      - /lib/firmware:/lib/firmware
  autoformat:
    autoformat:
      image: rancher/os-autoformat:v0.4.0-dev
      labels:
        io.rancher.os.detach: false
        io.rancher.os.scope: system
      log_driver: json-file
      net: none
      privileged: true
    udev-autoformat:
      image: rancher/os-udev:v0.4.0-dev
      labels:
        io.rancher.os.detach: false
        io.rancher.os.scope: system
        io.rancher.os.after: autoformat
      log_driver: json-file
      net: host
      uts: host
      privileged: true
      volumes:
      - /dev:/host/dev
      - /lib/modules:/lib/modules
      - /lib/firmware:/lib/firmware
  bootstrap_docker:
    args: [-d, -s, overlay, -b, none, --restart=false, -g, /var/lib/system-docker,
        -G, root, -H, 'unix:///var/run/system-docker.sock', --userland-proxy=false]
  cloud_init:
    datasources:
    - configdrive:/media/config-2
  services_include: {}
  network:
    dns:
      nameservers: [8.8.8.8, 8.8.4.4]
    interfaces:
      eth*:
        dhcp: true
      lo:
        address: 127.0.0.1/8
  repositories:
    core:
      url: https://raw.githubusercontent.com/rancherio/os-services/v0.4.0
  state:
    fstype: auto
    dev: LABEL=RANCHER_STATE
  services:
    acpid:
      image: rancher/os-acpid:v0.4.0-dev
      labels:
        io.rancher.os.scope: system
      net: host
      uts: host
      privileged: true
      volumes_from:
      - command-volumes
      - system-volumes
    all-volumes:
      image: rancher/os-state:v0.4.0-dev
      labels:
        io.rancher.os.createonly: true
        io.rancher.os.scope: system
      log_driver: json-file
      net: none
      privileged: true
      read_only: true
      volumes_from:
      - docker-volumes
      - command-volumes
      - user-volumes
      - system-volumes
    cloud-init:
      image: rancher/os-cloudinit:v0.4.0-dev
      labels:
        io.rancher.os.detach: false
        io.rancher.os.reloadconfig: true
        io.rancher.os.scope: system
        io.rancher.os.after: cloud-init-pre,network
      net: host
      uts: host
      privileged: true
      volumes_from:
      - command-volumes
      - system-volumes
    cloud-init-pre:
      image: rancher/os-cloudinit:v0.4.0-dev
      environment:
      - CLOUD_INIT_NETWORK=false
      labels:
        io.rancher.os.detach: false
        io.rancher.os.reloadconfig: true
        io.rancher.os.scope: system
        io.rancher.os.after: preload-system-images
      net: host
      uts: host
      privileged: true
      volumes_from:
      - command-volumes
      - system-volumes
    command-volumes:
      image: rancher/os-state:v0.4.0-dev
      labels:
        io.rancher.os.createonly: true
        io.rancher.os.scope: system
      log_driver: json-file
      net: none
      privileged: true
      read_only: true
      volumes:
      - /usr/bin/ros:/sbin/halt:ro
      - /usr/bin/ros:/sbin/poweroff:ro
      - /usr/bin/ros:/sbin/reboot:ro
      - /usr/bin/ros:/sbin/shutdown:ro
      - /usr/bin/ros:/sbin/netconf:ro
      - /usr/bin/ros:/usr/bin/cloud-init:ro
      - /usr/bin/ros:/usr/bin/rancherctl:ro
      - /usr/bin/ros:/usr/bin/ros:ro
      - /usr/bin/ros:/usr/bin/respawn:ro
      - /usr/bin/ros:/usr/bin/system-docker:ro
      - /usr/bin/ros:/usr/sbin/wait-for-docker:ro
      - /usr/bin/ros:/usr/bin/dockerlaunch:ro
      - /usr/bin/docker:/usr/bin/docker.dist:ro
    console:
      image: rancher/os-console:v0.4.0-dev
      labels:
        io.rancher.os.scope: system
        io.rancher.os.after: cloud-init
      net: host
      uts: host
      pid: host
      ipc: host
      privileged: true
      restart: always
      volumes_from:
      - all-volumes
    docker-volumes:
      image: rancher/os-state:v0.4.0-dev
      labels:
        io.rancher.os.createonly: true
        io.rancher.os.scope: system
      log_driver: json-file
      net: none
      privileged: true
      read_only: true
      volumes:
      - /var/lib/docker:/var/lib/docker
    network:
      image: rancher/os-network:v0.4.0-dev
      labels:
        io.rancher.os.detach: false
        io.rancher.os.scope: system
        io.rancher.os.after: cloud-init-pre
      net: host
      uts: host
      privileged: true
      volumes_from:
      - command-volumes
      - system-volumes
    ntp:
      image: rancher/os-ntp:v0.4.0-dev
      labels:
        io.rancher.os.scope: system
        io.rancher.os.after: cloud-init, network
      net: host
      uts: host
      privileged: true
      restart: always
    preload-system-images:
      image: rancher/os-preload:v0.4.0-dev
      labels:
        io.rancher.os.detach: false
        io.rancher.os.scope: system
      privileged: true
      volumes:
      - /var/run/system-docker.sock:/var/run/docker.sock
      - /var/lib/system-docker/preload:/mnt/preload
      volumes_from:
      - command-volumes
      - system-volumes
    preload-user-images:
      image: rancher/os-preload:v0.4.0-dev
      labels:
        io.rancher.os.detach: false
        io.rancher.os.scope: system
        io.rancher.os.after: console
      privileged: true
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/preload:/mnt/preload
      volumes_from:
      - command-volumes
      - system-volumes
    syslog:
      image: rancher/os-syslog:v0.4.0-dev
      labels:
        io.rancher.os.scope: system
      log_driver: json-file
      net: host
      uts: host
      privileged: true
      restart: always
      volumes_from:
      - system-volumes
    system-volumes:
      image: rancher/os-state:v0.4.0-dev
      labels:
        io.rancher.os.createonly: true
        io.rancher.os.scope: system
      log_driver: json-file
      net: none
      privileged: true
      read_only: true
      volumes:
      - /dev:/host/dev
      - /usr/share/ros/os-config.yml:/usr/share/ros/os-config.yml
      - /var/lib/rancher:/var/lib/rancher
      - /var/lib/rancher/conf:/var/lib/rancher/conf
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt.rancher
      - /lib/modules:/lib/modules
      - /lib/firmware:/lib/firmware
      - /run:/run
      - /var/run:/var/run
      - /var/log:/var/log
    udev-cold:
      image: rancher/os-udev:v0.4.0-dev
      labels:
        io.rancher.os.scope: system
        io.rancher.os.before: udev
      net: host
      uts: host
      privileged: true
      volumes_from:
      - system-volumes
    udev:
      image: rancher/os-udev:v0.4.0-dev
      environment:
      - DAEMON=true
      labels:
        io.rancher.os.detach: true
        io.rancher.os.scope: system
      net: host
      uts: host
      privileged: true
      restart: always
      volumes_from:
      - system-volumes
    user-volumes:
      image: rancher/os-state:v0.4.0-dev
      labels:
        io.rancher.os.createonly: true
        io.rancher.os.scope: system
      log_driver: json-file
      net: none
      privileged: true
      read_only: true
      volumes:
      - /home:/home
      - /opt:/opt
  system_docker:
    args: [-d, -s, overlay, -b, docker-sys, --fixed-cidr, 172.18.42.1/16,
      --restart=false, -g, /var/lib/system-docker, -G, root,
      -H, 'unix:///var/run/system-docker.sock', --userland-proxy=false]
  upgrade:
    url: https://releases.rancher.com/os/versions.yml
    image: rancher/os
  user_docker:
    tls_args: [--tlsverify, --tlscacert=ca.pem, --tlscert=server-cert.pem, --tlskey=server-key.pem,
      '-H=0.0.0.0:2376']
    args: [-d, -s, overlay, -G, docker, -H, 'unix:///var/run/docker.sock', --userland-proxy=false]
