name: release

on:
  workflow_dispatch:
    inputs:
      firmware:
        description: 'Include firmwares'
        default: 'true'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Install github-release
      run: |
        wget -O - -o /dev/null https://github.com/github-release/github-release/releases/download/v0.9.0/linux-amd64-github-release.bz2 | bunzip2 | sudo tee /usr/local/bin/github-release
        sudo chmod 0755 /usr/local/bin/github-release

    - name: Build OS
      run: |
        export VERSION=$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))
        if [ -z "$VERSION" ]; then
          echo "Build is not started from tag. Will exit..."
          exit 1
        fi
        export OS_FIRMWARE=${{ github.event.inputs.firmware }}
        export ARCH=amd64
        make release

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish release
      run: ${PWD}/dist/publish.sh
      env:
        GITHUB_TOKEN: ${{ secrets.OS_RELEASE_TOKEN }}
